---
name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r srcs/backend/requirements.txt

    - name: Run linting and formatting checks
      run: |
        black --check . --config srcs/backend/pyproject.toml
        isort --check-only . --settings-path srcs/backend/.isort.cfg
        flake8 . --config srcs/backend/.flake8
